### ISSUE TITLE
Download packages to cache failing due to unknown IP address

### ISSUE THREAD

**Issue by greole** [gerlero/setup-openfoam#53]
Currently, we observe failing workflows due to an unknown IP adresss error. 
```
  Err:1 https://dl.openfoam.com/repos/deb noble/main amd64 openfoam2406 amd64 2406.241212-1
    404  Not Found [IP: 172.67.128.143 443]
```

Don't know if that is a temporal thing or something that has changed. 

Example: 
https://github.com/exasim-project/FoamAdapter/actions/runs/12501553784/job/34879234430?pr=29

**Comment by gerlero** [comment]
@greole Can you try again? I've run the CI here and it seems to be working now

**Comment by greole** [comment]
Thanks for checking! I can confirm that it is working in our workflow too.
